# trigger:
#   branches:
#     include: ["master", "*"]

# pr:
#   branches:
#     include:
#     - '*'

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    ls

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav-prod'
    languages: 'csharp,typescript,java'
    githubServiceConnection: 'arjun27 (5)'
